name: Pipeline
on: [push]
jobs:
  setup-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Run docker file
        run: docker build -t action:v1 .
